[package]
name = "misato-desktop"
version = "0.1.0"
description = "MISATO Desktop Shell"
authors = ["MISATO"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-single-instance = "2.4.2"
tauri-plugin-window-state = "2.4.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
